# Generated by Django 4.2.6 on 2023-10-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0002_userregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userregistration",
            name="email",
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="password",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="repassword",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="username",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
