# Generated by Django 4.2.6 on 2023-10-15 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0003_alter_userregistration_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the animal (e.g., Dog, Cat)",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Enter the breed name", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Enter a brief description of the breed"
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        help_text="Select the animal type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeds",
                        to="Home.animal",
                    ),
                ),
            ],
        ),
    ]
