# Generated by Django 5.1.4 on 2025-01-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_userregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
