# Generated by Django 3.1.12 on 2025-01-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20250127_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Dog', 'Dog Accessories'), ('Cat', 'Cat Accessories'), ('Bird', 'Bird Accessories'), ('Fish', 'Fish Accessories'), ('Reptile', 'Reptile Accessories')], max_length=50)),
            ],
        ),
    ]
