# Generated by Django 3.1.12 on 2025-01-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_accessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='No description available')),
                ('animal_type', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='adoptions/')),
            ],
        ),
        migrations.RemoveField(
            model_name='breed',
            name='animal',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='category',
        ),
        migrations.AddField(
            model_name='accessory',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
    ]
