# Generated by Django 3.1.12 on 2025-01-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20250129_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='accessories/'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='adoptions/'),
        ),
    ]
