# Generated by Django 3.1.12 on 2025-01-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20250129_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='name',
        ),
        migrations.AddField(
            model_name='adoption',
            name='animal_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='adoption',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adoption',
            name='breed',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='description',
            field=models.TextField(),
        ),
    ]
