# Generated by Django 3.1.12 on 2025-01-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
